TurismoRuralComunitario/Controllers/CuentaController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using TurismoRuralComunitario.Helpers;
using TurismoRuralComunitario.Models;
using TurismoRuralComunitario.Request;

namespace TurismoRuralComunitario.Controllers
{
    public class CuentaController : BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Email,Password")] LoginRequest usuario)
        {
            if (ModelState.IsValid)
            {
                var existe = db.TablaUsuarios.Where(x => x.Password.Equals(usuario.Password)
                && x.Email.Equals(usuario.Email)).FirstOrDefault();

                if (existe != null)
                {
                    string rol = db.TablaRoles.Where(x => x.Id == existe.RolId).Select(x => x.TipoRol).FirstOrDefault();
                    GuardarCookies(existe.Email, rol, existe.Id);
                    if (existe.RolId == (int)Rol.Roles.AdministradorMunicipal)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else if (existe.RolId == (int)Rol.Roles.SuperAdministrador)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else if (existe.RolId == (int)Rol.Roles.Cliente)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else if (existe.RolId == (int)Rol.Roles.Propietario)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else if (existe.RolId == (int)Rol.Roles.Guia)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                }
                else
                {
                    SetAlert(Constantes.ALERT_ERROR);
                    SetMessage("Contraseña y/o email invalido.");
                    return RedirectToAction("Login");
                }

            }
            return View(usuario);
        }

        public ActionResult Registrarse()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrarse([Bind(Include = "Email,Password,Nombre,Cedula")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                var existe = ExisteCorreo(usuario.Email);
                var existecedula = ExisteCedula(usuario.Cedula);

                if (existe != null || existecedula)
                {
                    if (existecedula)
                    {
                        SetAlert(Constantes.ALERT_ERROR);
                        SetMessage("Cédula ya registrada..");
                    }
                    else
                    {
                        SetAlert(Constantes.ALERT_ERROR);
                        SetMessage("Email ya registrado.");
                    }
                    return RedirectToAction("Registrarse");
                }

                usuario.RolId = (int)Rol.Roles.Cliente;
                db.TablaUsuarios.Add(usuario);
                db.SaveChanges();
                SetAlert(Constantes.ALERT_SUCCESS);
                SetMessage("Registro satisfactoriamente.");
                return RedirectToAction("Login");
            }

            return View(usuario);
        }



        public ActionResult RecuperarPassword()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult RecuperarPassword([Bind(Include = "Email")] string Email)
        {
            if (ModelState.IsValid)
            {
                var persona = ExisteCorreo(Email);
                if (persona != null)
                {
                    persona.Token = Helper.Encriptar(JsonConvert.SerializeObject(persona));
                    persona.VencimientoToken = DateTime.Now.AddHours(4);
                    Helper.enviarCorreo(persona.Email, persona.Token, "Recuperación Contraseña");
                    try
                    {
                        db.Entry(persona).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                    SetAlert(Constantes.ALERT_SUCCESS);
                    SetMessage("Revise su bandeja de su correo eléctronico.");
                    return RedirectToAction("Login");
                }
                else
                {
                    SetAlert(Constantes.ALERT_ERROR);
                    SetMessage("No hay ningún usuario con ese email.");
                    return RedirectToAction("RecuperarContraseña");
                }
            }
            return View();
        }


        public ActionResult CambiarPassword(string token)
        {
            if (!string.IsNullOrEmpty(token))
            {
                var existe = BuscarUsuarioByToken(token);

                if (existe != null && existe.VencimientoToken > DateTime.Now)
                {
                    TempData["token"] = token;
                    return View();
                }
                else
                {
                    return RedirectToAction("Login");
                }
            }
            return RedirectToAction("Login");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ChangePassword(ChangePasswordRequest cambio)
        {
            if (ModelState.IsValid)
            {
                if (TempData["token"] != null)
                {
                    var usuario = BuscarUsuarioByToken(TempData["token"].ToString());
                    if (usuario != null)
                    {
                        usuario.Token = null;
                        usuario.VencimientoToken = null;
                        usuario.Password = cambio.Password;
                        try
                        {
                            db.Entry(usuario).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            throw ex;
                        }
                        SetAlert(Constantes.ALERT_SUCCESS);
                        SetMessage("Su contraseña se ha cambiado satisfactoriamente..");
                        return RedirectToAction("Login");
                    }
                }
            }
            return View("CambiarPassword");
        }


        [HttpPost]
        public ActionResult CerrarSesion()
        {
            if (User.Identity.IsAuthenticated)
            {
                Session.Clear();
                Request.GetOwinContext().Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                Response.Cookies.Clear();
                HttpCookie c = new HttpCookie("Login");
                c.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(c);
                Session.Abandon();
            }
            Session.Abandon();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private Usuario ExisteCorreo(string correo)
        {
            return db.TablaUsuarios.Where(x => x.Email.Equals(correo)).FirstOrDefault();
        }
        private bool ExisteCedula(string cedula)
        {
            return db.TablaUsuarios.Any(x => x.Cedula.Equals(cedula));
        }

        private Usuario BuscarUsuarioByToken(string token)
        {
            return db.TablaUsuarios.Where(x => x.Token.Equals(token)).FirstOrDefault();
        }

    }
}

TurismoRuralComunitario/Views/Cuenta/CambiarPassword.cshtml
@model TurismoRuralComunitario.Request.ChangePasswordRequest
@{
    ViewBag.Title = "Cambiar Contraseña";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container py-5 mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="form-group col-lg-5">
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <h4 class="text-center mb-sm-5 mb-4 text-dark">Cambiar Contraseña</h4>
                    @using (Html.BeginForm("ChangePassword", "Cuenta", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-key"></i>
                                </div>
                            </div>
                            @Html.PasswordFor(model => model.Password, new { @placeholder = "contraseña", @class = "form-control" })
                        </div>
                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.ConfirmarPassword, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-key"></i>
                                </div>
                            </div>
                            @Html.PasswordFor(model => model.ConfirmarPassword, new { @placeholder = "confirmar contraseña", @class = "form-control" })
                        </div>
                        <div class=" form-group text-center col-lg-12 mb-4">
                            <button type="submit" class="btn btn-secondary btn-block"><strong>Cambiar Contraseña</strong><i class="fas fa-share-square ml-3"></i></button>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TurismoRuralComunitario/Views/Cuenta/Login.cshtml
@model TurismoRuralComunitario.Request.LoginRequest
@using TurismoRuralComunitario.Helpers
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container py-5 mt-5 mb-5">
    <div class="form-group row justify-content-center">
        <div class="@TempData[Constantes.ALERT] alert-dismissible fade show" role="alert">
            <strong>@TempData[Constantes.MESSAGE]</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="form-group col-lg-5">
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <h4 class="text-center mb-sm-5 mb-4 text-dark">Login</h4>
                    @using (Html.BeginForm("Login", "Cuenta", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-envelope"></i>
                                </div>
                            </div>
                            @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email", @class = "form-control", @type = "email" })
                        </div>
                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-auto input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-key"></i>
                                </div>
                            </div>
                            @Html.PasswordFor(model => model.Password, new { @placeholder = "Contraseña", @class = "form-control" })
                        </div>

                        <div class=" form-group text-center col-lg-12 mb-4">
                            <button type="submit" class="btn btn-secondary btn-block"><i class="fas fa-sign-in-alt mr-2"></i><strong>Iniciar sesión</strong></button>
                        </div>
                        <div class="form-row justify-content-start ml-1">
                            <h6 class="btn btn-link">@Html.ActionLink("¿Olvidaste tu contraseña?", "RecuperarPassword")</h6>
                        </div>
                        <hr />
                        <div class="row justify-content-center mb-2 mt-4">
                            <h6 class="text-black-50 font-italic font-weight-bold">¿No tienes cuenta aún?</h6>
                        </div>
                        <div class="row justify-content-center mt-4">
                            <a class="btn btn-link text-black-50 font-weight-bold" href="@Url.Action("Registrarse")">Crea Tu Cuenta</a>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TurismoRuralComunitario/Views/Cuenta/RecuperarPassword.cshtml
@model TurismoRuralComunitario.Request.LoginRequest
@using TurismoRuralComunitario.Helpers
@{
    ViewBag.Title = "Recuperación Contraseña";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container py-5 mt-5 mb-5">
    <div class="form-group row justify-content-center">
        <div class="@TempData[Constantes.ALERT] alert-dismissible fade show" role="alert">
            <strong>@TempData[Constantes.MESSAGE]</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="form-group col-lg-5">
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <h4 class="text-center mb-sm-5 mb-4 text-dark">Recuperar Contraseña</h4>
                    @using (Html.BeginForm("RecuperarPassword", "Cuenta", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-envelope"></i>
                                </div>
                            </div>
                            @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email", @class = "form-control", @type = "email" })
                        </div>
                        <div class=" form-group text-center col-lg-12 mb-4">
                            <button type="submit" class="btn btn-secondary btn-block"><strong>Enviar</strong><i class="fas fa-share-square ml-3"></i></button>
                        </div>
                        <hr />
                        <div class="row justify-content-center mt-4">
                            <a class="btn btn-link text-black-50 font-weight-bold" href="@Url.Action("Login")"><i class="fas fa-chevron-circle-left"></i> salir</a>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TurismoRuralComunitario/Views/Cuenta/Registrarse.cshtml
@model TurismoRuralComunitario.Models.Usuario
@using TurismoRuralComunitario.Helpers

@{
    ViewBag.Title = "Registrarse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container py-5 mt-5 mb-5">
    <div class="form-group row justify-content-center">
        <div class="@TempData[Constantes.ALERT] alert-dismissible fade show" role="alert">
            <strong>@TempData[Constantes.MESSAGE]</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="form-group col-lg-6">
            <div class="card bg-light mb-3">
                <div class="card-body">
                    <h4 class="text-center mb-sm-5 mb-3 text-dark">Registro</h4>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-user"></i>
                                </div>
                            </div>
                            @Html.TextBoxFor(model => model.Nombre, new { @placeholder = "Nombre completo", @class = "form-control" })
                        </div>


                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-envelope"></i>
                                </div>
                            </div>
                            @Html.TextBoxFor(model => model.Email, new { @placeholder = "Email", @class = "form-control", @type = "email" })
                        </div>

                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-12 input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-address-card"></i>
                                </div>
                            </div>
                            @Html.TextBoxFor(model => model.Cedula, new { @placeholder = "Cédula", @class = "form-control" })
                        </div>

                        <div class="form-row justify-content-lg-start ml-3">
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-lg-auto input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fa fa-key"></i>
                                </div>
                            </div>
                            @Html.PasswordFor(model => model.Password, new { @placeholder = "Contraseña", @class = "form-control" })
                        </div>
                        <div class=" form-group text-center col-lg-12 mb-4">
                            <button type="submit" class="btn btn-info btn-block"><strong>Registrarse</strong><i class="fas fa-hand-point-right ml-2"></i></button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}