TurismoRuralComunitario/Models/Tour.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Web;
using TurismoRuralComunitario.Helpers;

namespace TurismoRuralComunitario.Models
{
    [Table("tour", Schema = "tours")]
    public class Tour
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("municipio_id")]
        public int? MunicipioId { get; set; }

        [Column("nombre_del_sitio")]
        [Display(Name = "Nombre del tour")]
        [Required(ErrorMessage = "*")]
        public string NombreSitio { get; set; }

        [Column("precio")]
        [Required(ErrorMessage = "*")]
        [Display(Name = "Precio del tour")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public double Precio { get; set; }

        [Column("path_imagen")]
        [Display(Name = "Imagen")]
        public string PathImagen { get; set; }

        [Column("descripcion_tour")]
        public string DescripcionTour { get; set; }

        [NotMapped]
        [ValidImageFile(ErrorMessage = "Es incorrecto el formato.")]
        public HttpPostedFileBase Imagen { get; set; }

        [NotMapped]
        [Display(Name = "Municipio")]
        public string Municipio { get; set; }

        [NotMapped]
        public DetallesDelTour Detalles { get; set; } = new DetallesDelTour();
        public class ValidImageFileAttribute : ValidationAttribute
        {
            public override bool IsValid(object value)
            {
                if (value == null)
                    return true;

                string[] _validExtensions = { "JPG", "JPEG", "BMP", "GIF", "PNG" };

                var file = (HttpPostedFileBase)value;
                var ext = Path.GetExtension(file.FileName).ToUpper().Replace(".", "");
                return _validExtensions.Contains(ext) && file.ContentType.Contains("image");
            }
        }
    }

    public class DetallesDelTour
    {
        [Display(Name = "Registro nacional de turismo")]
        [Required(ErrorMessage = "*")]
        public string RegistroNacionalDeTurismo { get; set; }
        [Display(Name = "Total de habitaciones")]
        [Required(ErrorMessage = "*")]
        public int TotalHabitaciones { get; set; }
        [Display(Name = "Caracteristicas del tour")]
        [Required(ErrorMessage = "*")]
        public string Caracteristicas { get; set; }
    }
}

TurismoRuralComunitario/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web.Mvc;
using TurismoRuralComunitario.Helpers;
using TurismoRuralComunitario.Models;

namespace TurismoRuralComunitario.Controllers
{
    public class TourController : BaseController
    {
        private List<Tour> catalogoTours = new List<Tour>();
        private DatabaseContext db = new DatabaseContext();

        #region catalogo tours

        public async Task<ActionResult> Catalogo()
        {
            return View(await ListarCatalogo());
        }

        private async Task<List<Tour>> ListarCatalogo()
        {
            var usuario = await db.TablaUsuarios.FindAsync(ObtenerIdxClaim());

            if (usuario != null)
            {
                catalogoTours = usuario.MunicipioId == null ? await db.TablaTour.ToListAsync()
                    : await db.TablaTour.Where(x => x.MunicipioId == usuario.MunicipioId).ToListAsync();
            }
            else
            {
                catalogoTours = await db.TablaTour.ToListAsync();
            }

            foreach (var item in catalogoTours)
            {
                item.Detalles = JsonSerializer.Deserialize<DetallesDelTour>(item.DescripcionTour);
            }
            return catalogoTours;
        }

        #endregion

        #region Detalles del tour
        public async Task<ActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                SetMessage("No existe ese tour.");
                return Redirect("Catalogo");
            }
            Tour tour = await db.TablaTour.FindAsync(id);
            tour.Municipio = db.TablaMunicipios.Find(tour.MunicipioId).NombreMunicipio;
            if (tour == null)
            {
                SetMessage("No existe ese tour.");
                return Redirect("Catalogo");
            }
            tour.Detalles = JsonSerializer.Deserialize<DetallesDelTour>(tour.DescripcionTour);
            return View(tour);
        }

        #endregion
        
        #region crear
        [Authorize(Roles = Constantes.ADMIN + "," + Constantes.ADMINMUNICIPAL)]
        public ActionResult Crear()
        {
            ListaCantidadHabitaciones();
            return View();
        }

        private void ListaCantidadHabitaciones()
        {
            List<int> habitaciones = new List<int>()
            {
                1,2,3,4,5,6
            };

            ViewBag.DDL_CantidadHabitaciones = new SelectList(habitaciones);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear(Tour tour)
        {
            if (ModelState.IsValid)
            {
                FolderIsExist(Constantes.PATH_IMAGENES_TOURS);
                if (tour.Imagen != null && tour.Imagen.ContentLength > 0)
                {
                    string extension = Path.GetExtension(tour.Imagen.FileName);
                    PathCompleto = ConcatenarPath(Constantes.PATH_IMAGENES_TOURS, tour.NombreSitio, extension);
                    string path = Server.MapPath(PathCompleto);
                    subirArchivo(tour.PathImagen, path, tour.Imagen);
                    tour.PathImagen = PathCompleto;
                }
                json = JsonSerializer.Serialize(tour.Detalles);
                tour.DescripcionTour = json;

                var municipio = await db.TablaUsuarios.FindAsync(ObtenerIdxClaim());

                tour.MunicipioId = municipio.MunicipioId != null ? municipio.MunicipioId : null;
                db.TablaTour.Add(tour);
                await db.SaveChangesAsync();
                return Redirect("Catalogo");
            }

            ListaCantidadHabitaciones();
            return View(tour);
        }

        #endregion

        #region Editar

        [Authorize(Roles = Constantes.ADMIN + "," + Constantes.ADMINMUNICIPAL)]
        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                SetMessage("No existe ese tour.");
                return Redirect("Catalogo");
            }
            Tour tourEdit = await db.TablaTour.FindAsync(id);
            if (tourEdit == null)
            {
                SetMessage("No existe ese tour.");
                return Redirect("Catalogo");
            }
            tourEdit.Detalles = JsonSerializer.Deserialize<DetallesDelTour>(tourEdit.DescripcionTour);
            ListaCantidadHabitaciones();
            return View(tourEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditarAsync(Tour newTour)
        {
            if (ModelState.IsValid)
            {
                if (newTour.Imagen != null && newTour.Imagen.ContentLength > 0)
                {
                    string extension = Path.GetExtension(newTour.Imagen.FileName);
                    PathCompleto = ConcatenarPath(Constantes.PATH_IMAGENES_TOURS, newTour.NombreSitio, extension);
                    string path = Server.MapPath(PathCompleto);
                    subirArchivo(newTour.PathImagen, path, newTour.Imagen);
                    newTour.PathImagen = PathCompleto;
                }
                json = JsonSerializer.Serialize(newTour.Detalles);
                newTour.DescripcionTour = json;
                db.Entry(newTour).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Redirect("Catalogo");
            }
            return View(newTour);
        }
        #endregion

        #region Eliminar
        [Authorize(Roles = Constantes.ADMIN + "," + Constantes.ADMINMUNICIPAL)]
        public async Task<ActionResult> Eliminar(int id)
        {
            var tour = db.TablaTour.Find(id);
            if (!string.IsNullOrEmpty(tour.PathImagen))
            {
                EliminarArchivo(tour.PathImagen);
            }
            db.TablaTour.Remove(tour);
            await db.SaveChangesAsync();
            return RedirectToAction("Catalogo");
        }
#endregion
    }
}

TurismoRuralComunitario/Views/Tour/Catalogo.cshtml
@model IEnumerable<TurismoRuralComunitario.Models.Tour>
@using TurismoRuralComunitario.Models
@{
    ViewBag.Title = "Creación de tour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<title>@ViewBag.Title</title>
<section class="w3l-pricing-11">
    <div class="pricing11 py-5">
        <div class="container py-md-4">
            <div class="w3l-header mb-md-5 mb-4 text-center">
                <h6 class="sub-title">Nuestros tours</h6>
                <h3 class="hny-title">Catalogo</h3>
            </div>
            @if (Model.Count() == 0)
            {
                <div class="row justify-content-center">
                    <div class="alert alert-info justify-content-center" role="alert">
                        <strong>No hay productos en stock por el momento.</strong>
                    </div>
                </div>
            }
            else
            {
                <div class="pricing11-content">
                    @foreach (var item in Model)
                    {

                        <div class="column pricing-grid">
                            <div class="rate mb-2">
                                <h3><span class="text-center mb-2"></span>@item.NombreSitio</h3>
                            </div>
                            <div class="text-center price-icon">
                                @if (!string.IsNullOrEmpty(item.PathImagen))
                                {
                                    <img src="@Url.Content(item.PathImagen)" class="img-thumbnail img-fluid" />
                                }
                                else
                                {
                                    <img src="~/Recursos/imgTours/defaultMunicipio.png" class="img-thumbnail img-fluid" />
                                }
                            </div>
                            <div class="rate mb-2">
                                <h4>Precio:</h4>
                                <h5><span class="top-align"></span>@Html.DisplayFor(modelItem => item.Precio)</h5>
                            </div>
                            <div class="text-center">
                                <a href="@Url.Action("Detalle","Tour", new { id = item.Id})" class="btn btn-secondary btn-lg btn-block">Ver más</a>
                            </div>
                            @if (Request.IsAuthenticated)
                            {
                                if (User.IsInRole(Rol.Roles.SuperAdministrador.ToString()) || User.IsInRole(Rol.Roles.AdministradorMunicipal.ToString()))
                                {
                                    <div class="row justify-content-between mt-4">
                                        <div class="col">
                                            <a href="@Url.Action("Editar",new { id = item.Id})" class="btn btn-info btn-sm btn-block text-white"><i class="fa fa-edit mr-2"></i>Editar</a>
                                        </div>
                                        <div class="col">
                                            <a onclick="eliminar(@item.Id)" class="btn btn-danger btn-sm btn-block text-white"><i class="fa fa-trash mr-2"></i>Eliminar</a>
                                        </div>
                                    </div>
                                }
                            }
                        </div>

                    }
                </div>
            }

        </div>
    </div>
</section>

@section scripts{
    <script type="text/javascript">
        var success = '<i class="mr-2 fa fa-check-circle"></i>';
        var error = '<i class="mr-2 fa fa-times-circle"> </i>';
        $(function () {
            var mensaje = '@TempData[TurismoRuralComunitario.Helpers.Constantes.MESSAGE]'
            if (mensaje != '') {
                if (mensaje.indexOf("existe") > -1) {
                    alertify.error(error+mensaje);
                }
                else {
                    alertify.success(success+mensaje);
                }
            }
        });
        function eliminar(id) {
            alertify.confirm('Eliminando', '¿Esta seguro de eliminar este tour?',
                function () {
                    window.location.href = '@Url.Action("Eliminar", "Tour")/' + id;
                }, function () {
                    alertify.error('Cancelado');
            }).set('labels', { ok: 'Ok', cancel: 'Cancelar' });
        }
    </script>
}

TurismoRuralComunitario/Views/Tour/Crear.cshtml
@model TurismoRuralComunitario.Models.Tour
@{
    ViewBag.Title = "Creación de tour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<title>@ViewBag.Title</title>
@using (Html.BeginForm("Crear", "Tour", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
  
<section class="w3l-contact-11 py-5">
    <div class="container">
        <a href="@Url.Action("Catalogo")" class="btn btn-style-1 mb-3"><i class="fas fa-arrow-alt-circle-left mr-2"></i><strong>Cancelar</strong></a>
    </div>
    <div class="contacts-main py-lg-5 py-md-4">
        <div class="title-content text-center">
            <h6 class="sub-title">Crear</h6>
            <h3 class="hny-title">Tour</h3>
        </div>
    </div>
    <div class="form-41-mian section-gap mt-5">
        <div class="container">
            <div class="d-grid align-form-map">
                <div class="form-inner-cont">
                    <form class="signin-form">
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.NombreSitio)</strong>
                            @Html.ValidationMessageFor(model => model.NombreSitio, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.NombreSitio)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Precio)</strong>
                            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.Precio)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Detalles.RegistroNacionalDeTurismo)</strong>
                            @Html.ValidationMessageFor(model => model.Detalles.RegistroNacionalDeTurismo, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.Detalles.RegistroNacionalDeTurismo)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Detalles.Caracteristicas)</strong>
                            @Html.ValidationMessageFor(model => model.Detalles.Caracteristicas, "", new { @class = "text-danger" })
                            @Html.TextAreaFor(model => model.Detalles.Caracteristicas)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Detalles.TotalHabitaciones)</strong>
                            @Html.ValidationMessageFor(model => model.Detalles.TotalHabitaciones, "", new { @class = "text-danger" })
                            @Html.DropDownListFor(x => x.Detalles.TotalHabitaciones, ViewBag.DDL_CantidadHabitaciones as SelectList, "Seleccione total de habitaciones")

                        </div>


                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.PathImagen)</strong>
                            @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                            <div class="custom-file">
                                @Html.TextBoxFor(model => model.Imagen, htmlAttributes: new { @class = "custom-file-input", @lang = "es", @type = "file", @accept = "image/png,image/jpg,image/bmp,image/gif,image/jpeg" })
                                <label class="custom-file-label" for="validatedCustomFile">
                                    <i class="fa fa-file-image mr-4"></i><strong>Seleccionar archivo....</strong>
                                </label>
                            </div>
                        </div>
                        <div class="form-submit text-center mt-4">
                            <button type="submit" class="btn btn-secondary btn-lg"><i class="fa fa-plus-circle mr-2"></i>Agregar</button>
                        </div>
                    </form>
                </div>
                <div class="col align-self-center text-center mb-5">
                    <br />
                    <img id="imagenmuestra" src="~/Recursos/imgTours/defaultMunicipio.png" class="img-fluid rounded" width="450" height="450" />
                </div>
            </div>
        </div>
    </div>
</section>
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        $('input[type=file]').change(function () {
            var val = $(this).val().toLowerCase(),
                regex = new RegExp("(.*?)\.(jpeg|jpg|png)$");

            if (!(regex.test(val))) {
                $(this).val();
                alert("Ingrese un archivo valido de imagen");
            }
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    // Asignamos el atributo src a la tag de imagen
                    $('#imagenmuestra').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        // El listener va asignado al input
        $("#Imagen").change(function () {
            readURL(this);
        });
    </script>
}

TurismoRuralComunitario/Views/Tour/CrearTour.cshtml
@model TurismoRuralComunitario.Models.Tour
@{
    ViewBag.Title = "Creación de tour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<title>@ViewBag.Title</title>
@using (Html.BeginForm("CrearTour", "Tour", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
  
<section class="w3l-contact-11 py-5">
    <div class="container">
        <a href="@Url.Action("Catalogo")" class="btn btn-style-1 mb-3"><i class="fas fa-arrow-alt-circle-left mr-2"></i><strong>Cancelar</strong></a>
    </div>
    <div class="contacts-main py-lg-5 py-md-4">
        <div class="title-content text-center">
            <h6 class="sub-title">Crear</h6>
            <h3 class="hny-title">Tour</h3>
        </div>
    </div>
    <div class="form-41-mian section-gap mt-5">
        <div class="container">
            <div class="d-grid align-form-map">
                <div class="form-inner-cont">
                    <form class="signin-form">
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.NombreSitio)</strong>
                            @Html.ValidationMessageFor(model => model.NombreSitio, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.NombreSitio)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Precio)</strong>
                            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.Precio)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Detalles.RegistroNacionalDeTurismo)</strong>
                            @Html.ValidationMessageFor(model => model.Detalles.RegistroNacionalDeTurismo, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.Detalles.RegistroNacionalDeTurismo)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Detalles.Caracteristicas)</strong>
                            @Html.ValidationMessageFor(model => model.Detalles.Caracteristicas, "", new { @class = "text-danger" })
                            @Html.TextAreaFor(model => model.Detalles.Caracteristicas)
                        </div>
                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.Detalles.TotalHabitaciones)</strong>
                            @Html.ValidationMessageFor(model => model.Detalles.TotalHabitaciones, "", new { @class = "text-danger" })
                            @Html.DropDownListFor(x => x.Detalles.TotalHabitaciones, ViewBag.DDL_CantidadHabitaciones as SelectList, "Seleccione total de habitaciones")

                        </div>


                        <div class="form-input">
                            <strong>@Html.LabelFor(model => model.PathImagen)</strong>
                            @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                            <div class="custom-file">
                                @Html.TextBoxFor(model => model.Imagen, htmlAttributes: new { @class = "custom-file-input", @lang = "es", @type = "file", @accept = "image/png,image/jpg,image/bmp,image/gif,image/jpeg" })
                                <label class="custom-file-label" for="validatedCustomFile">
                                    <i class="fa fa-file-image mr-4"></i><strong>Seleccionar archivo....</strong>
                                </label>
                            </div>
                        </div>
                        <div class="form-submit text-center mt-4">
                            <button type="submit" class="btn btn-secondary btn-lg"><i class="fa fa-plus-circle mr-2"></i>Agregar</button>
                        </div>
                    </form>
                </div>
                <div class="col align-self-center text-center mb-5">
                    <br />
                    <img id="imagenmuestra" src="~/Recursos/imgTours/defaultMunicipio.png" class="img-fluid rounded" width="450" height="450" />
                </div>
            </div>
        </div>
    </div>
</section>
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        $('input[type=file]').change(function () {
            var val = $(this).val().toLowerCase(),
                regex = new RegExp("(.*?)\.(jpeg|jpg|png)$");

            if (!(regex.test(val))) {
                $(this).val();
                alert("Ingrese un archivo valido de imagen");
            }
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    // Asignamos el atributo src a la tag de imagen
                    $('#imagenmuestra').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        // El listener va asignado al input
        $("#Imagen").change(function () {
            readURL(this);
        });
    </script>
}

TurismoRuralComunitario/Views/Tour/Editar.cshtml
@model TurismoRuralComunitario.Models.Tour
@{
    ViewBag.Title = "Creación de tour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<title>@ViewBag.Title</title>
@using (Html.BeginForm("EditarAsync", "Tour", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.PathImagen)
    @Html.HiddenFor(model => model.MunicipioId)
    <section class="w3l-contact-11 py-5">
        <div class="container">
            <a href="@Url.Action("Catalogo")" class="btn btn-style-1 mb-3"><i class="fas fa-arrow-alt-circle-left mr-2"></i><strong>Cancelar</strong></a>
        </div>
        <div class="contacts-main py-lg-5 py-md-4">
            <div class="title-content text-center">
                <h6 class="sub-title">Editar</h6>
                <h3 class="hny-title">Tour</h3>
            </div>
        </div>
        <div class="form-41-mian section-gap mt-5" id="DatosRespuesta">
            <div class="container">
                <div class="d-grid align-form-map">
                    <div class="form-inner-cont">
                        <form class="signin-form">
                            <div class="form-input">
                                <strong>@Html.LabelFor(model => model.NombreSitio)</strong>
                                @Html.ValidationMessageFor(model => model.NombreSitio, "", new { @class = "text-danger" })
                                @Html.EditorFor(model => model.NombreSitio)
                            </div>
                            <div class="form-input">
                                <strong>@Html.LabelFor(model => model.Precio)</strong>
                                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                                @Html.EditorFor(model => model.Precio)
                            </div>
                            <div class="form-input">
                                <strong>@Html.LabelFor(model => model.Detalles.RegistroNacionalDeTurismo)</strong>
                                @Html.ValidationMessageFor(model => model.Detalles.RegistroNacionalDeTurismo, "", new { @class = "text-danger" })
                                @Html.EditorFor(model => model.Detalles.RegistroNacionalDeTurismo)
                            </div>
                            <div class="form-input">
                                <strong>@Html.LabelFor(model => model.Detalles.Caracteristicas)</strong>
                                @Html.ValidationMessageFor(model => model.Detalles.Caracteristicas, "", new { @class = "text-danger" })
                                @Html.TextAreaFor(model => model.Detalles.Caracteristicas)
                            </div>
                            <div class="form-input">
                                <strong>@Html.LabelFor(model => model.Detalles.TotalHabitaciones)</strong>
                                @Html.ValidationMessageFor(model => model.Detalles.TotalHabitaciones, "", new { @class = "text-danger" })
                                @Html.DropDownListFor(x => x.Detalles.TotalHabitaciones, ViewBag.DDL_CantidadHabitaciones as SelectList, "Seleccione total de habitaciones")

                            </div>


                            <div class="form-input">
                                <strong>@Html.LabelFor(model => model.PathImagen)</strong>
                                @Html.ValidationMessageFor(model => model.Imagen, "", new { @class = "text-danger" })
                                <div class="custom-file">
                                    @Html.TextBoxFor(model => model.Imagen, htmlAttributes: new { @class = "custom-file-input", @lang = "es", @type = "file", @accept = "image/png,image/jpg,image/bmp,image/gif,image/jpeg" })
                                    <label class="custom-file-label" for="validatedCustomFile">
                                        <i class="fa fa-file-image mr-4"></i><strong>Seleccionar archivo....</strong>
                                    </label>
                                </div>
                            </div>
                            <div class="form-submit text-center mt-4">
                                <button type="submit" class="btn btn-info btn-lg"><i class="fa fa-edit mr-2"></i>Editar</button>
                            </div>
                        </form>
                    </div>
                    <div class="col align-self-center text-center mb-5">
                        <br />
                        @if (!string.IsNullOrEmpty(Model.PathImagen))
                        {
                            <img id="imagenmuestra" src="@Url.Content(Model.PathImagen)" class="img-fluid rounded" width="450" height="450" />
                        }
                        else
                        {
                            <img id="imagenmuestra" src="~/Recursos/imgTours/defaultMunicipio.png" class="img-fluid rounded" width="450" height="450" />
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        $('input[type=file]').change(function () {
            var val = $(this).val().toLowerCase(),
                regex = new RegExp("(.*?)\.(jpeg|jpg|png)$");

            if (!(regex.test(val))) {
                $(this).val();
                alert("Ingrese un archivo valido de imagen");
            }
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    // Asignamos el atributo src a la tag de imagen
                    $('#imagenmuestra').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        // El listener va asignado al input
        $("#Imagen").change(function () {
            readURL(this);
        });
    </script>
}